/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link TokenParameters}
 * @category Accounts
 * @category generated
 */
export type TokenParametersArgs = {
  tokenOwner: web3.PublicKey
  mint: web3.PublicKey
  metadata: web3.PublicKey
  primarySalePrice: beet.bignum
  maxSupply: number
  primarySaleTokenLimit: number
  numberOfSales: number
  platformFeeBasisPoints: number
  creatorFeeBasisPoints: number
}

export const tokenParametersDiscriminator = [
  178, 81, 154, 250, 181, 189, 19, 181,
]
/**
 * Holds the data for the {@link TokenParameters} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class TokenParameters implements TokenParametersArgs {
  private constructor(
    readonly tokenOwner: web3.PublicKey,
    readonly mint: web3.PublicKey,
    readonly metadata: web3.PublicKey,
    readonly primarySalePrice: beet.bignum,
    readonly maxSupply: number,
    readonly primarySaleTokenLimit: number,
    readonly numberOfSales: number,
    readonly platformFeeBasisPoints: number,
    readonly creatorFeeBasisPoints: number
  ) {}

  /**
   * Creates a {@link TokenParameters} instance from the provided args.
   */
  static fromArgs(args: TokenParametersArgs) {
    return new TokenParameters(
      args.tokenOwner,
      args.mint,
      args.metadata,
      args.primarySalePrice,
      args.maxSupply,
      args.primarySaleTokenLimit,
      args.numberOfSales,
      args.platformFeeBasisPoints,
      args.creatorFeeBasisPoints
    )
  }

  /**
   * Deserializes the {@link TokenParameters} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [TokenParameters, number] {
    return TokenParameters.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link TokenParameters} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey
  ): Promise<TokenParameters> {
    const accountInfo = await connection.getAccountInfo(address)
    if (accountInfo == null) {
      throw new Error(`Unable to find TokenParameters account at ${address}`)
    }
    return TokenParameters.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'GeTddTEvfE8My8HNbnSeS1o2tzyn9Z4S194tCUZPbQ8Y'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, tokenParametersBeet)
  }

  /**
   * Deserializes the {@link TokenParameters} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [TokenParameters, number] {
    return tokenParametersBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link TokenParameters} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return tokenParametersBeet.serialize({
      accountDiscriminator: tokenParametersDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link TokenParameters}
   */
  static get byteSize() {
    return tokenParametersBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link TokenParameters} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      TokenParameters.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link TokenParameters} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === TokenParameters.byteSize
  }

  /**
   * Returns a readable version of {@link TokenParameters} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      tokenOwner: this.tokenOwner.toBase58(),
      mint: this.mint.toBase58(),
      metadata: this.metadata.toBase58(),
      primarySalePrice: (() => {
        const x = <{ toNumber: () => number }>this.primarySalePrice
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      maxSupply: this.maxSupply,
      primarySaleTokenLimit: this.primarySaleTokenLimit,
      numberOfSales: this.numberOfSales,
      platformFeeBasisPoints: this.platformFeeBasisPoints,
      creatorFeeBasisPoints: this.creatorFeeBasisPoints,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const tokenParametersBeet = new beet.BeetStruct<
  TokenParameters,
  TokenParametersArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['tokenOwner', beetSolana.publicKey],
    ['mint', beetSolana.publicKey],
    ['metadata', beetSolana.publicKey],
    ['primarySalePrice', beet.u64],
    ['maxSupply', beet.u32],
    ['primarySaleTokenLimit', beet.u32],
    ['numberOfSales', beet.u32],
    ['platformFeeBasisPoints', beet.u16],
    ['creatorFeeBasisPoints', beet.u16],
  ],
  TokenParameters.fromArgs,
  'TokenParameters'
)
